import { createApi } from '@reduxjs/toolkit/query/react';
import { fetchBaseQuery } from '@reduxjs/toolkit/query';

import { authApisEndPoints } from '../../consts/apiEndPoints';
// import baseQueryWithReauth from "../../../utils/baseQueryWithReauth";

export const authApis = createApi({
  reducerPath: 'authApis',
  // baseQuery: baseQueryWithReauth,
  baseQuery: fetchBaseQuery({ baseUrl: 'https://jsonplaceholder.typicode.com/' }),
  tagTypes: ['AuthApis'],

  endpoints: (builder) => ({
    signIn: builder.mutation({
      query: (credentials) => ({
        url: authApisEndPoints.signInApisEndPoint,
        method: 'POST',
        body: credentials,
      }),
    }),

    signUp: builder.mutation({
      query: (credentials) => ({
        url: authApisEndPoints.signUpApiEndPoint,
        method: 'POST',
        body: credentials,
      }),
    }),
  }),
});

export const authApiReducer = authApis.reducer;
export const authApiReducerPath = authApis.reducerPath;
export const authApiMiddleware = authApis.middleware;

// Hooks auto-generated by RTK Query
export const { useSignInMutation, useSignUpMutation } = authApis;
