import { createApi } from '@reduxjs/toolkit/query/react';
import { fetchBaseQuery } from '@reduxjs/toolkit/query';
import { dashboardApiEndPoints } from '../../consts/apiEndPoints';

export const dashboardApis = createApi({
  reducerPath: 'dashboardApis',
  baseQuery: fetchBaseQuery({ baseUrl: 'https://fakestoreapi.com' }),
  tagTypes: ['DashboardApi'],

  endpoints: (builder) => ({
    getProductsList: builder.query({
      query: () => ({
        url: dashboardApiEndPoints.productsApiEndPoint,
        method: 'Get',
        providesTags: ['DashboardApi'],

        transformResponse: (response) => {
          return response.map((product) => ({
            ...product,
            discountedPrice: (product.price * 0.9).toFixed(2), // 10% discount
          }));
        },
      }),
    }),
  }),
});

export const dashboardApiReducer = dashboardApis.reducer;
export const dashboardApiReducerPath = dashboardApis.reducerPath;
export const dashboardApiMiddleware = dashboardApis.middleware;

// Hooks auto-generated by RTK Query
export const { useGetProductsListQuery } = dashboardApis;
